version: '3'

services:
    app:
        build: .
        entrypoint: ./.docker/entrypoint.sh
        container_name: strapi
        ports:
          - 1337:1337
        volumes:
          - .:/home/node/app
