version: '3.9'
services:
###NODERED##########
  node-red:
    container_name: mynodered
    image: nodered/node-red:latest
    ports:
      - 1880:1880
    volumes:
      - ./nodered-data:/data
    networks:
      - compose-bridge

##RABBITMQ#######
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: my-rabbitmq
    container_name: rabbitmq
    command: "/bin/bash -c \"rabbitmq-plugins enable rabbitmq_mqtt; rabbitmq-server\""
    ports:
      - 5672:5672
      - 15672:15672
      - 1883:1883
    networks:
      - compose-bridge  
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=pass123
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/

networks:
  compose-bridge:
    driver: bridge